### PR TITLE
Customizable placement of editor / toggle window

### PR DESCRIPTION
**Pull request by bambuschop**
#### Checklist

- [x] only relevant code is changed (make a diff before you submit the PR)
- [ ] run tests `npm run test`
- [ ] tests are included
- [x] documentation is changed or added

#### What does this PR change?

This PR adds the option to specify a few custom modifiers to enable better integration of the InContext Editor into existing projects.
* The InContext Editor can be placed within an existing `<div>` Element on a page by passing a `document.querySelector('.class')` Element within the `init()` function.
* The InContext Editor can receive custom classes, making it easier to style via CSS
* The "Click to Select" toggle container can be placed within an existing `<div>` Element on a page by passing a `document.querySelecot('.class')` Element within the `init()` function.
* The "Click to Select" toggle container can receive custom classes, making it easier to style via CSS
* The "Click to Select" toggle can receive a custom title, giving the possibility to explain the user what the button does.
* The `index.html` of the `debuggingApp` was modified to reflect the new changes in a disabled state, making it easier to debug them if needed by enabling them.

All of those changes are opt-in. If no new options are provided, the InContext Editor and "Clic kto Select" toggle will behave exactly the same as before.

### CODE REVIEW

**Comment by adrai** [comment]
lgtm

**Review by jamuhl — APPROVED** [review]

**Comment by jamuhl** [comment]
lgtm... @bambuschop just as an early hint...we're currently working on a refresh of the locize UI...adding some new features. InContext editing will change rather drastically.

**Comment by bambuschop** [comment]
@jamuhl sounds good, looking forward on the refresh! We are using Locize heavily and every improvement in the future is welcome. 👍

**Comment by adrai** [comment]
Thank you for your contribution.
It has been released with v3.1.0

**Pull request merged**
